# /etc/nginx/sites-available/workflows_app

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name workflows-dev.parliament.gov.za;

    ssl_certificate "/etc/pki/tls/certs/server.crt";
    ssl_certificate_key "/etc/pki/tls/private/server.key";
    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  10m;
    ssl_ciphers PROFILE=SYSTEM;
    ssl_prefer_server_ciphers on;


    # Client body size limit
    client_max_body_size 10M;

    # Proxy requests to Gunicorn
    location / {
        # proxy_pass http://unix:/var/run/gunicorn.sock;
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve static files directly
    location /staticfiles/ {
        alias /home/admgelie/Projects/pwms/staticfiles/;
    }

    # Serve media files directly
    location /media/ {
        alias /home/admgelie/Projects/pwms/media/;
    }
}
