# Generated by Django 6.0.3 on 2026-06-03 11:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('drive_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_transition_workflows', models.BooleanField(default=False, help_text='Users with this role can perform state transitions on workflows')),
                ('can_create_workflows', models.BooleanField(default=False, help_text='Users with this role can create new workflows for their groups')),
                ('can_assign_workflows', models.BooleanField(default=False, help_text='Users with this role can assign workflows to other users')),
                ('can_manage_permissions', models.BooleanField(default=False, help_text='Users with this role can grant/revoke workflow access to other groups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharePointToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='SharePoint access token')),
                ('refresh_token', models.TextField(blank=True, help_text='SharePoint refresh token')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False, help_text='Is this the initial state?')),
                ('is_terminal', models.BooleanField(default=False, help_text='Is this a final state?')),
                ('allows_referrals', models.BooleanField(default=True, help_text='Can workflows in this state be referred to other groups?')),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#5b8f22', help_text='Hex color code', max_length=7)),
            ],
            options={
                'ordering': ['workflow_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('hon', 'Hon.'), ('rt_hon', 'Rt. Hon.')], max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('employee_type', models.CharField(blank=True, choices=[('staff', 'Staff'), ('member', 'Member'), ('graduate', 'Graduate')], max_length=10)),
                ('positiondesc', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('idno_encrypted', models.TextField(blank=True)),
                ('idno_hmac', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_mp', models.BooleanField(default=False, help_text='Is this user a Member of Parliament?')),
                ('is_staff_member', models.BooleanField(default=False, help_text='Is this user a staff member?')),
                ('constituency', models.CharField(blank=True, max_length=200)),
                ('party_affiliation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_joined_parliament', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.eventtype')),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflows.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('group_type', models.CharField(choices=[('legislature', 'Legislature'), ('house', 'House'), ('portfolio_committee', 'Portfolio Committee'), ('select_committee', 'Select Committee'), ('special_committee', 'Special Committee'), ('public_accounts_committee', 'Public Accounts Committee'), ('internal_committee', 'Internal Committee'), ('ad_hoc_committee', 'Ad Hoc Committee'), ('joint_committee', 'Joint Committee'), ('administration', 'Administration'), ('office', 'Office'), ('division', 'Division'), ('section', 'Section'), ('business_unit', 'Business Unit'), ('party', 'Party'), ('executive', 'Executive'), ('presidency', 'Presidency'), ('ministry', 'Ministry'), ('department', 'Department'), ('province', 'Province'), ('premier', 'Premier'), ('delegation', 'Delegation')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflows.group')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflows.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.group'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('site_id', models.CharField(max_length=200)),
                ('is_personal_site', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this record was last refreshed from SharePoint.')),
                ('remote_modified_at', models.DateTimeField(blank=True, help_text='The last modified timestamp reported by SharePoint for this site.', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharePointFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('folder_id', models.CharField(help_text='SharePoint folder ID', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('web_url', models.URLField(blank=True, help_text='Direct URL to folder in SharePoint', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.drive')),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='workflows.sharepointfolder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.site')),
            ],
            options={
                'ordering': ['site', 'drive', 'name'],
                'unique_together': {('site', 'drive', 'folder_id')},
            },
        ),
        migrations.AddField(
            model_name='drive',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.site'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('drive_id', models.CharField(help_text='SharePoint drive ID', max_length=200)),
                ('item_id', models.CharField(help_text='SharePoint item ID', max_length=200)),
                ('mimetype', models.CharField(blank=True, help_text='MIME type of the file', max_length=200, null=True)),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_url', models.URLField(blank=True, help_text='SharePoint download URL', null=True)),
                ('sharepoint_web_url', models.URLField(blank=True, help_text='Direct SharePoint web URL', null=True)),
                ('sharepoint_folder_path', models.CharField(blank=True, help_text='Folder path in SharePoint', max_length=500)),
                ('type', models.CharField(choices=[('response', 'Response'), ('document', 'Document'), ('petition', 'Petition'), ('other', 'Other')], max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sharepoint_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.drive')),
                ('sharepoint_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.sharepointfolder')),
                ('sharepoint_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_transition', models.BooleanField(default=False, help_text='Can perform transitions from this state (overrides Transition.allowed_roles if set)')),
                ('roles', models.ManyToManyField(related_name='state_permissions', to='workflows.role')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='workflows.state')),
            ],
            options={
                'ordering': ['state'],
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('requires_comment', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('allowed_roles', models.ManyToManyField(related_name='allowed_transitions', to='workflows.role')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflows.state')),
                ('notify_roles', models.ManyToManyField(blank=True, help_text='Group members with these roles will receive an email alert when this transition occurs', related_name='notified_transitions', to='workflows.role')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflows.state')),
            ],
            options={
                'ordering': ['workflow_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='workflows.building')),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflows.venue'),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Workflow-specific attributes')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('attachments', models.ManyToManyField(blank=True, to='workflows.attachment')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='workflows.state')),
                ('event', models.ForeignKey(blank=True, help_text='Event this workflow is associated with', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='workflows.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workflows', to=settings.AUTH_USER_MODEL)),
                ('parent_workflow', models.ForeignKey(blank=True, help_text='Parent workflow (e.g., International Report for Resolutions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflows', to='workflows.workflow')),
                ('referred_to_groups', models.ManyToManyField(blank=True, help_text='Groups this workflow is referred to', related_name='referred_workflows', to='workflows.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_instance', to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, help_text='Supporting documents attached to this comment', related_name='comments', to='workflows.attachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflows.workflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='related_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary owning group (typically selected at creation)')),
                ('inherited_from_type', models.BooleanField(default=False, help_text='Access was inherited from WorkflowType configuration (legacy)')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_workflow_access', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_access', to='workflows.group')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-is_primary', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_transition', models.BooleanField(default=False)),
                ('allowed_states', models.ManyToManyField(blank=True, help_text='If specified, these permissions only apply in these states', related_name='role_workflow_permissions', to='workflows.state')),
                ('group_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='workflows.workflowgroupaccess')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_permissions', to='workflows.role')),
            ],
            options={
                'ordering': ['role__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_logs_from', to='workflows.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_logs_to', to='workflows.state')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.transition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('json_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema defining additional fields for this workflow type')),
                ('create_roles', models.ManyToManyField(related_name='create_workflow_types', to='workflows.role')),
                ('group', models.ForeignKey(help_text='The group that owns all workflows of this type', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_types', to='workflows.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.workflowtype'),
        ),
        migrations.AddField(
            model_name='transition',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowtype'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflows.workflowtype'),
        ),
        migrations.CreateModel(
            name='WorkflowTypeChildConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('relationship_label', models.CharField(help_text="Human-readable label for this relationship (e.g. 'Resolution', 'Amendment')", max_length=100)),
                ('relationship_key', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text="Slug-like key stored on the child Workflow instance (e.g. 'resolution')", populate_from='relationship_label', unique=True)),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_as_child_of', to='workflows.workflowtype')),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_child_configs', to='workflows.workflowtype')),
            ],
            options={
                'ordering': ['parent_type', 'relationship_label'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='relationship_type',
            field=models.ForeignKey(blank=True, help_text='Predefined relationship type to parent workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='workflows.workflowtypechildconfig'),
        ),
        migrations.CreateModel(
            name='WorkflowTypeReferralConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text="Optional label for this referral route (e.g. 'For comment', 'For decision')", max_length=100)),
                ('referred_edit_roles', models.ManyToManyField(blank=True, help_text='Roles in the referred group allowed to edit the workflow', related_name='referral_edit_configs', to='workflows.role')),
                ('referred_transition_roles', models.ManyToManyField(blank=True, help_text='Roles in the referred group allowed to perform transitions', related_name='referral_transition_configs', to='workflows.role')),
                ('target_group', models.ForeignKey(help_text='Group that workflows of this type can be referred to', on_delete=django.db.models.deletion.CASCADE, related_name='referral_configs_as_target', to='workflows.group')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_configs', to='workflows.workflowtype')),
            ],
            options={
                'ordering': ['workflow_type', 'target_group'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Reason for the referral')),
                ('deadline', models.DateTimeField(blank=True, help_text='Deadline for referral response (optional)', null=True)),
                ('deadline_notified', models.BooleanField(default=False, help_text='Whether deadline notifications have been sent')),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('recalled_at', models.DateTimeField(blank=True, null=True)),
                ('recall_reason', models.TextField(blank=True)),
                ('recalled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_recalled', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referred_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_referrals', to='workflows.group')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='workflows.workflow')),
                ('config', models.ForeignKey(blank=True, help_text='The referral config that governs permissions for this referral (deprecated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_instances', to='workflows.workflowtypereferralconfig')),
            ],
            options={
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('transition', 'Transition')], max_length=12)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='workflows_a_content_358053_idx'), models.Index(fields=['user', 'timestamp'], name='workflows_a_user_id_b9bb7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('absent', 'Absent'), ('apology', 'Apology')], default='invited', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workflows.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'user'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workflows.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.role')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('user', 'group', 'role', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='SiteMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('site', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the delegation becomes effective')),
                ('end_date', models.DateTimeField(blank=True, help_text='When the delegation expires (null = indefinite)', null=True)),
                ('can_view_workflows', models.BooleanField(default=True, help_text="Delegatee can view delegator's workflows")),
                ('can_edit_workflows', models.BooleanField(default=False, help_text="Delegatee can edit delegator's workflows")),
                ('can_transition_workflows', models.BooleanField(default=False, help_text="Delegatee can perform transitions on delegator's workflows")),
                ('can_receive_assignments', models.BooleanField(default=True, help_text='New workflow assignments to delegator go to delegatee')),
                ('can_receive_notifications', models.BooleanField(default=True, help_text="Delegatee receives delegator's workflow notifications")),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='active', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the delegation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this delegation was approved', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this delegation was revoked', null=True)),
                ('revoke_reason', models.TextField(blank=True, help_text='Reason for revoking the delegation')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this delegation (if required)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegatee', models.ForeignKey(help_text='User who receives the delegated permissions', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='User who is delegating their permissions', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_made', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='Specific groups this delegation applies to (empty = all groups)', related_name='delegations', to='workflows.group')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this delegation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to=settings.AUTH_USER_MODEL)),
                ('workflows', models.ManyToManyField(blank=True, help_text='Specific workflows this delegation applies to (empty = all workflows)', related_name='delegations', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delegator', 'status'], name='workflows_u_delegat_c83735_idx'), models.Index(fields=['delegatee', 'status'], name='workflows_u_delegat_a3a2ff_idx'), models.Index(fields=['start_date', 'end_date'], name='workflows_u_start_d_a05957_idx'), models.Index(fields=['status', 'end_date'], name='workflows_u_status_0f306a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='delegation_end_after_start')],
                'unique_together': {('delegator', 'delegatee', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('transition', 'Transition'), ('assigned', 'Assigned'), ('referred', 'Referred'), ('comment', 'Comment'), ('overdue', 'Overdue'), ('pending', 'Pending Deadline'), ('delegation_created', 'Delegation Created'), ('delegation_approved', 'Delegation Approved'), ('delegation_revoked', 'Delegation Revoked'), ('delegation_expired', 'Delegation Expired'), ('deadline_warning', 'Deadline Warning'), ('auto_recall', 'Auto Recall')], default='transition', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='workflows_n_user_id_e2f3eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_a_content_e23568_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['related_workflow'], name='workflows_a_related_8e8f22_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['sharepoint_site', 'sharepoint_drive'], name='workflows_a_sharepo_ddbb71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('related_workflow', 'item_id')},
        ),
        migrations.AddIndex(
            model_name='workflowgroupaccess',
            index=models.Index(fields=['workflow', 'group'], name='workflows_w_workflo_e8041c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowgroupaccess',
            index=models.Index(fields=['group'], name='workflows_w_group_i_4b65f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowgroupaccess',
            unique_together={('workflow', 'group')},
        ),
        migrations.AddIndex(
            model_name='workflowrolepermission',
            index=models.Index(fields=['group_access', 'role'], name='workflows_w_group_a_6cc95a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowrolepermission',
            unique_together={('group_access', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('workflow_type', 'from_state', 'to_state')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow_type', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowtypechildconfig',
            unique_together={('parent_type', 'child_type')},
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workflow_type', 'current_state'], name='workflows_w_workflo_fcb681_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['deadline'], name='workflows_w_deadlin_bb5d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['parent_workflow'], name='workflows_w_parent__b558e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_workflow_id')), _negated=True), name='workflow_not_self_parent'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtypereferralconfig',
            unique_together={('workflow_type', 'target_group')},
        ),
    ]
