# Generated by Django 6.0.3 on 2026-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('ms', 'Ms.'), ('mrs', 'Mrs.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('hon', 'Hon.'), ('rt_hon', 'Rt. Hon.')], max_length=30),
        ),
    ]
