# Generated by Django 6.0.1 on 2026-02-12 13:11

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("drive_id", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("can_create_workflows", models.BooleanField(default=False)),
                ("can_edit_workflows", models.BooleanField(default=False)),
                ("can_delete_workflows", models.BooleanField(default=False)),
                ("can_view_all_workflows", models.BooleanField(default=False)),
                ("can_manage_members", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SharePointToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(help_text="SharePoint access token")),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="SharePoint refresh token"),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this token is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_initial",
                    models.BooleanField(
                        default=False, help_text="Is this the initial state?"
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False, help_text="Is this a final state?"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        default="#6B7280", help_text="Hex color code", max_length=7
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("facilities", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "json_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON schema defining additional fields for this workflow type",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="constituency",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined_parliament",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("staff", "Staff"),
                    ("member", "Member"),
                    ("graduate", "Graduate"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="idno_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="idno_hmac",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_mp",
            field=models.BooleanField(
                default=False, help_text="Is this user a Member of Parliament?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff_member",
            field=models.BooleanField(
                default=False, help_text="Is this user a staff member?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="party_affiliation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="positiondesc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mr", "Mr."),
                    ("ms", "Ms."),
                    ("mrs", "Mrs."),
                    ("dr", "Dr."),
                    ("prof", "Prof."),
                    ("hon", "Hon."),
                    ("rt_hon", "Rt. Hon."),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("legislature", "Legislature"),
                            ("house", "House"),
                            ("portfolio_committee", "Portfolio Committee"),
                            ("select_committee", "Select Committee"),
                            ("special_committee", "Special Committee"),
                            ("public_accounts_committee", "Public Accounts Committee"),
                            ("internal_committee", "Internal Committee"),
                            ("ad_hoc_committee", "Ad Hoc Committee"),
                            ("joint_committee", "Joint Committee"),
                            ("administration", "Administration"),
                            ("office", "Office"),
                            ("division", "Division"),
                            ("section", "Section"),
                            ("business_unit", "Business Unit"),
                            ("party", "Party"),
                            ("executive", "Executive"),
                            ("presidency", "Presidency"),
                            ("ministry", "Ministry"),
                            ("department", "Department"),
                            ("province", "Province"),
                            ("premier", "Premier"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="workflows.group",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflows.group",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                (
                    "allowed_roles",
                    models.ManyToManyField(related_name="facets", to="workflows.role"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("site_id", models.CharField(max_length=200)),
                ("is_personal_site", models.BooleanField(default=False)),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this record was last refreshed from SharePoint.",
                    ),
                ),
                (
                    "remote_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last modified timestamp reported by SharePoint for this site.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SharePointFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(help_text="SharePoint folder ID", max_length=200),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "web_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to folder in SharePoint",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.drive",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="workflows.sharepointfolder",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
                    ),
                ),
            ],
            options={
                "ordering": ["site", "drive", "name"],
                "unique_together": {("site", "drive", "folder_id")},
            },
        ),
        migrations.AddField(
            model_name="drive",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
            ),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "drive_id",
                    models.CharField(help_text="SharePoint drive ID", max_length=200),
                ),
                (
                    "item_id",
                    models.CharField(help_text="SharePoint item ID", max_length=200),
                ),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True, help_text="SharePoint download URL", null=True
                    ),
                ),
                (
                    "sharepoint_web_url",
                    models.URLField(
                        blank=True, help_text="Direct SharePoint web URL", null=True
                    ),
                ),
                (
                    "sharepoint_folder_path",
                    models.CharField(
                        blank=True,
                        help_text="Folder path in SharePoint",
                        max_length=500,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("response", "Response"),
                            ("document", "Document"),
                            ("petition", "Petition"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sharepoint_drive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.drive",
                    ),
                ),
                (
                    "sharepoint_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.sharepointfolder",
                    ),
                ),
                (
                    "sharepoint_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("requires_comment", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "allowed_roles",
                    models.ManyToManyField(
                        related_name="allowed_transitions", to="workflows.role"
                    ),
                ),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_from",
                        to="workflows.state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions_to",
                        to="workflows.state",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="workflows.workflowtype",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "relationship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resolution", "Resolution"),
                            ("amendment", "Amendment"),
                            ("follow_up", "Follow-up Action"),
                            ("supplement", "Supplementary Document"),
                            ("correction", "Correction/Erratum"),
                        ],
                        help_text="Type of relationship to parent workflow",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Workflow-specific attributes",
                    ),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(blank=True, to="workflows.attachment"),
                ),
                (
                    "current_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows",
                        to="workflows.state",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="workflows.group",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent workflow (e.g., International Report for Resolutions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_workflows",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group this workflow is referred to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referred_workflows",
                        to="workflows.group",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflows.workflowtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflows.eventtype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="workflows.group",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflows.venue",
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="related_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.workflow",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowTransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_logs_from",
                        to="workflows.state",
                    ),
                ),
                (
                    "to_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transition_logs_to",
                        to="workflows.state",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflows.transition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transition_logs",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="state",
            name="workflow_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="workflows.workflowtype",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="workflows_a_content_358053_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="workflows_a_user_id_b9bb7b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("confirmed", "Confirmed"),
                            ("attended", "Attended"),
                            ("absent", "Absent"),
                            ("apology", "Apology"),
                        ],
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="workflows.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event", "user"],
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="workflows.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="workflows.role"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("user", "group", "role", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="StateFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.facet",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facets",
                        to="workflows.state",
                    ),
                ),
            ],
            options={
                "unique_together": {("state", "facet")},
            },
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflows_a_content_e23568_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["related_workflow"], name="workflows_a_related_8e8f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["sharepoint_site", "sharepoint_drive"],
                name="workflows_a_sharepo_ddbb71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["workflow_type", "current_state"],
                name="workflows_w_workflo_fcb681_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["group", "current_state"], name="workflows_w_group_i_7682e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["deadline"], name="workflows_w_deadlin_bb5d9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["parent_workflow"], name="workflows_w_parent__b558e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("id", models.F("parent_workflow_id")), _negated=True
                ),
                name="workflow_not_self_parent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transition",
            unique_together={("workflow_type", "from_state", "to_state")},
        ),
        migrations.AlterUniqueTogether(
            name="state",
            unique_together={("workflow_type", "name")},
        ),
    ]
