# Generated by Django 6.0.3 on 2026-06-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]
