# Generated by Django 6.0.1 on 2026-02-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_drive_eventtype_role_sharepointtoken_state_venue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="workflows.group",
            ),
        ),
    ]
