# Generated by Django 6.0.3 on 2026-06-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
