# Generated by Django 6.0.1 on 2026-02-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_remove_user_is_active_member_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facet",
            name="allowed_roles",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_view",
        ),
        migrations.AddField(
            model_name="facet",
            name="delete_roles",
            field=models.ManyToManyField(
                related_name="deletable_facets", to="workflows.role"
            ),
        ),
        migrations.AddField(
            model_name="facet",
            name="edit_roles",
            field=models.ManyToManyField(
                related_name="editable_facets", to="workflows.role"
            ),
        ),
        migrations.AddField(
            model_name="facet",
            name="view_roles",
            field=models.ManyToManyField(
                related_name="viewable_facets", to="workflows.role"
            ),
        ),
    ]
