# Generated by Django 6.0.1 on 2026-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0003_alter_groupmembership_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtype",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
