# Generated by Django 6.0.1 on 2026-02-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0004_remove_facet_allowed_roles_remove_facet_can_delete_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="facet",
            name="allowed_roles",
            field=models.ManyToManyField(related_name="facets", to="workflows.role"),
        ),
    ]
