# Generated by Django 6.0.1 on 2026-02-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_facet_allowed_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facet",
            name="delete_roles",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="edit_roles",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="view_roles",
        ),
        migrations.AddField(
            model_name="facet",
            name="can_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facet",
            name="can_edit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="facet",
            name="can_view",
            field=models.BooleanField(default=True),
        ),
    ]
