# Generated by Django 6.0.1 on 2026-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0006_add_permissions_to_role_and_facet"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflow",
            name="workflows_w_group_i_7682e2_idx",
        ),
        migrations.AlterField(
            model_name="facet",
            name="can_create",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facet",
            name="can_transition",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="can_create_subworkflows",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="can_manage_states",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="can_manage_workflow_types",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="role",
            name="can_transition_workflows",
            field=models.BooleanField(default=False),
        ),
    ]
