# Generated by Django 6.0.1 on 2026-02-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0006_remove_facet_delete_roles_remove_facet_edit_roles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="parent_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent workflow (e.g., International Report for Resolutions)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_workflows",
                to="workflows.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="relationship_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolution", "Resolution"),
                    ("amendment", "Amendment"),
                    ("follow_up", "Follow-up Action"),
                    ("supplement", "Supplementary Document"),
                    ("correction", "Correction/Erratum"),
                ],
                help_text="Type of relationship to parent workflow",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["parent_workflow"], name="workflows_w_parent__b558e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("id", models.F("parent_workflow_id")), _negated=True
                ),
                name="workflow_not_self_parent",
            ),
        ),
    ]
