# Generated by Django 6.0.1 on 2026-02-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_add_workflow_hierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "drive_id",
                    models.CharField(help_text="SharePoint drive ID", max_length=200),
                ),
                (
                    "item_id",
                    models.CharField(help_text="SharePoint item ID", max_length=200),
                ),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True, help_text="SharePoint download URL", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("response", "Response"),
                            ("document", "Document"),
                            ("petition", "Petition"),
                        ],
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.workflow",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workflow",
            name="attachments",
            field=models.ManyToManyField(blank=True, to="workflows.attachment"),
        ),
    ]
