# Generated by Django 6.0.1 on 2026-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0007_remove_workflow_workflows_w_group_i_7682e2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtype",
            name="create_roles",
            field=models.ManyToManyField(
                related_name="create_workflow_types", to="workflows.role"
            ),
        ),
    ]
