# Generated by Django 6.0.3 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0007_contract_generic_object_id_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="drive_id",
            field=models.CharField(help_text="SharePoint drive ID", max_length=512),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="item_id",
            field=models.CharField(help_text="SharePoint item ID", max_length=512),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="mimetype",
            field=models.CharField(
                blank=True,
                help_text="MIME type of the file",
                max_length=512,
                null=True,
            ),
        ),
    ]
