# Generated by Django 6.0.1 on 2026-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_workflowtype_create_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facet",
            name="allowed_roles",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_create",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_transition",
        ),
        migrations.RemoveField(
            model_name="facet",
            name="can_view",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_create_subworkflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_create_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_delete_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_edit_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_manage_members",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_manage_states",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_manage_workflow_types",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_transition_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_view_all_workflows",
        ),
        migrations.AddField(
            model_name="facet",
            name="delete_roles",
            field=models.ManyToManyField(
                blank=True, related_name="deletable_facets", to="workflows.role"
            ),
        ),
        migrations.AddField(
            model_name="facet",
            name="edit_roles",
            field=models.ManyToManyField(
                blank=True, related_name="editable_facets", to="workflows.role"
            ),
        ),
        migrations.AddField(
            model_name="facet",
            name="transition_roles",
            field=models.ManyToManyField(
                blank=True, related_name="transitionable_facets", to="workflows.role"
            ),
        ),
        migrations.AddField(
            model_name="facet",
            name="view_roles",
            field=models.ManyToManyField(
                blank=True, related_name="viewable_facets", to="workflows.role"
            ),
        ),
    ]
