# Generated by Django 6.0.1 on 2026-02-10 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0008_attachment_workflow_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("site_id", models.CharField(max_length=200)),
                ("is_personal_site", models.BooleanField(default=False)),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this record was last refreshed from SharePoint.",
                    ),
                ),
                (
                    "remote_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The last modified timestamp reported by SharePoint for this site.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("drive_id", models.CharField(max_length=200)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
