# Generated by Django 6.0.3 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0008_alter_attachment_field_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="download_url",
            field=models.URLField(
                blank=True,
                help_text="SharePoint download URL",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="sharepoint_web_url",
            field=models.URLField(
                blank=True,
                help_text="Direct SharePoint web URL",
                max_length=2048,
                null=True,
            ),
        ),
    ]
