# Generated by Django 6.0.1 on 2026-02-11 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("workflows", "0009_alter_attachment_options_site_drive_sitemember"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharePointToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(help_text="SharePoint access token")),
                (
                    "refresh_token",
                    models.TextField(blank=True, help_text="SharePoint refresh token"),
                ),
                ("expires_at", models.DateTimeField(help_text="Token expiration time")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this token is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="sharepoint_drive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.drive",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="sharepoint_folder_path",
            field=models.CharField(
                blank=True, help_text="Folder path in SharePoint", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="sharepoint_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.site",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="sharepoint_web_url",
            field=models.URLField(
                blank=True, help_text="Direct SharePoint web URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="related_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.workflow",
            ),
        ),
        migrations.CreateModel(
            name="SharePointFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(help_text="SharePoint folder ID", max_length=200),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "web_url",
                    models.URLField(
                        blank=True,
                        help_text="Direct URL to folder in SharePoint",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflows.drive",
                    ),
                ),
                (
                    "parent_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="workflows.sharepointfolder",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflows.site"
                    ),
                ),
            ],
            options={
                "ordering": ["site", "drive", "name"],
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="sharepoint_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.sharepointfolder",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="workflows_a_content_e23568_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["related_workflow"], name="workflows_a_related_8e8f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["sharepoint_site", "sharepoint_drive"],
                name="workflows_a_sharepo_ddbb71_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sharepointfolder",
            unique_together={("site", "drive", "folder_id")},
        ),
    ]
