# Generated by Django 6.0.1 on 2026-02-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflows",
            "0009_remove_facet_allowed_roles_remove_facet_can_create_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="group",
        ),
    ]
