# Generated by Django 6.0.1 on 2026-02-15 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0010_remove_workflow_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitemember",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitemember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
