# Generated by Django 6.0.1 on 2026-02-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0011_sitemember_date_joined_sitemember_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitemember",
            old_name="date_joined",
            new_name="date_added",
        ),
    ]
