# Generated by Django 6.0.1 on 2026-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0012_rename_date_joined_sitemember_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="transition",
            name="notify_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Group members with these roles will receive an email alert when this transition occurs",
                related_name="notified_transitions",
                to="workflows.role",
            ),
        ),
    ]
