# Generated by Django 6.0.1 on 2026-02-18 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("workflows", "0013_add_transition_notify_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("transition", "Transition"),
                    ("assigned", "Assigned"),
                    ("referred", "Referred"),
                    ("comment", "Comment"),
                ],
                default="transition",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="workflows.workflow",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="workflows_n_user_id_e2f3eb_idx"
            ),
        ),
    ]
