# Generated by Django 6.0.1 on 2026-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0014_add_notification_verb_workflow_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supporting documents attached to this comment",
                related_name="comments",
                to="workflows.attachment",
            ),
        ),
    ]
