# Generated by Django 6.0.1 on 2026-02-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0015_comment_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTypeChildConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_label",
                    models.CharField(
                        help_text="Human-readable label for this relationship (e.g. 'Resolution', 'Amendment')",
                        max_length=100,
                    ),
                ),
                (
                    "relationship_key",
                    models.SlugField(
                        help_text="Slug-like key stored on the child Workflow instance (e.g. 'resolution')"
                    ),
                ),
                (
                    "child_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_as_child_of",
                        to="workflows.workflowtype",
                    ),
                ),
                (
                    "parent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_child_configs",
                        to="workflows.workflowtype",
                    ),
                ),
            ],
            options={
                "ordering": ["parent_type", "relationship_label"],
                "unique_together": {("parent_type", "child_type")},
            },
        ),
        migrations.RunSQL(
            sql="UPDATE workflows_workflow SET relationship_type = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="workflow",
            name="relationship_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Predefined relationship type to parent workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_instances",
                to="workflows.workflowtypechildconfig",
            ),
        ),
        migrations.CreateModel(
            name="StatePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_permissions",
                        to="workflows.role",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="workflows.state",
                    ),
                ),
            ],
            options={
                "ordering": ["state", "role"],
                "unique_together": {("state", "role")},
            },
        ),
    ]
