# Generated by Django 6.0.1 on 2026-02-20 17:09

from django.db import migrations


def migrate_facets_to_state_permissions(apps, schema_editor):
    """
    For each StateFacet, merge the view/edit/delete role sets from the linked Facet
    into StatePermission rows (one per state+role pair, OR-ing the booleans).
    """
    StateFacet = apps.get_model("workflows", "StateFacet")
    StatePermission = apps.get_model("workflows", "StatePermission")

    for sf in StateFacet.objects.select_related("facet", "state").prefetch_related(
        "facet__view_roles", "facet__edit_roles", "facet__delete_roles"
    ):
        facet = sf.facet
        state = sf.state

        # Collect all roles referenced by this facet
        role_ids = set()
        role_ids.update(facet.view_roles.values_list("id", flat=True))
        role_ids.update(facet.edit_roles.values_list("id", flat=True))
        role_ids.update(facet.delete_roles.values_list("id", flat=True))

        view_role_ids = set(facet.view_roles.values_list("id", flat=True))
        edit_role_ids = set(facet.edit_roles.values_list("id", flat=True))
        delete_role_ids = set(facet.delete_roles.values_list("id", flat=True))

        for role_id in role_ids:
            perm, _ = StatePermission.objects.get_or_create(
                state=state,
                role_id=role_id,
                defaults={"can_view": False, "can_edit": False, "can_delete": False},
            )
            # OR the new permissions onto any existing row
            if role_id in view_role_ids:
                perm.can_view = True
            if role_id in edit_role_ids:
                perm.can_edit = True
            if role_id in delete_role_ids:
                perm.can_delete = True
            perm.save()


def reverse_migration(apps, schema_editor):
    StatePermission = apps.get_model("workflows", "StatePermission")
    StatePermission.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0016_add_workflow_type_child_config_and_state_permission"),
    ]

    operations = [
        migrations.RunPython(
            migrate_facets_to_state_permissions,
            reverse_code=reverse_migration,
        ),
    ]
