# Generated by Django 6.0.1 on 2026-02-20 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflows", "0017_migrate_facets_to_state_permissions"),
    ]

    operations = [
        migrations.DeleteModel(name="StateFacet"),
        migrations.DeleteModel(name="Facet"),
    ]
