# Generated by Django 6.0.1 on 2026-02-20 17:20

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0018_remove_facet_and_statefacet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowtypechildconfig",
            name="relationship_key",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="Slug-like key stored on the child Workflow instance (e.g. 'resolution')",
                populate_from="relationship_label",
                unique=True,
            ),
        ),
    ]
