# Generated by Django 6.0.1 on 2026-02-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0019_alter_workflowtypechildconfig_relationship_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("view", "View"),
                    ("transition", "Transition"),
                ],
                max_length=12,
            ),
        ),
    ]
