# Generated by Django 6.0.1 on 2026-02-23 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0020_auditlog_add_transition_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTypeReferralConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this referral route (e.g. 'For comment', 'For decision')",
                        max_length=100,
                    ),
                ),
                (
                    "referred_edit_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles in the referred group allowed to edit the workflow",
                        related_name="referral_edit_configs",
                        to="workflows.role",
                    ),
                ),
                (
                    "referred_transition_roles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Roles in the referred group allowed to perform transitions",
                        related_name="referral_transition_configs",
                        to="workflows.role",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        help_text="Group that workflows of this type can be referred to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_configs_as_target",
                        to="workflows.group",
                    ),
                ),
                (
                    "workflow_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_configs",
                        to="workflows.workflowtype",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow_type", "target_group"],
                "unique_together": {("workflow_type", "target_group")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the referral"),
                ),
                ("referred_at", models.DateTimeField(auto_now_add=True)),
                ("recalled_at", models.DateTimeField(blank=True, null=True)),
                ("recall_reason", models.TextField(blank=True)),
                (
                    "recalled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_recalled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referred_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_referrals",
                        to="workflows.group",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="workflows.workflow",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        help_text="The referral config that governs permissions for this referral",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_instances",
                        to="workflows.workflowtypereferralconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-referred_at"],
            },
        ),
    ]
