# Generated by Django 6.0.1 on 2026-02-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0021_referral_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("transition", "Transition"),
                    ("assigned", "Assigned"),
                    ("referred", "Referred"),
                    ("comment", "Comment"),
                    ("overdue", "Overdue"),
                ],
                default="transition",
                max_length=20,
            ),
        ),
    ]
