# Generated by Django 6.0.1 on 2026-02-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0023_eventcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ["building", "floor", "room_number", "name"]},
        ),
        migrations.RemoveField(
            model_name="venue",
            name="location",
        ),
        migrations.AddField(
            model_name="venue",
            name="floor",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="venue",
            name="room_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="venue",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="workflows.building",
            ),
        ),
    ]
