# Generated by Django 6.0.1 on 2026-03-06 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0025_location_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtype",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_types",
                to="workflows.event",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="color",
            field=models.CharField(
                default="#5b8f22", help_text="Hex color code", max_length=7
            ),
        ),
    ]
