# Generated by Django 6.0.1 on 2026-03-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0026_workflowtype_event_alter_state_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Event this workflow is associated with",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflows",
                to="workflows.event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="workflow",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_instance",
                to="workflows.workflow",
            ),
        ),
    ]
