# Generated by Django 6.0.1 on 2026-03-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0027_workflow_event_alter_event_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="workflowtype",
            name="event",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
