# Generated by Django 6.0.1 on 2026-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0028_alter_event_location_remove_workflowtype_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("transition", "Transition"),
                    ("assigned", "Assigned"),
                    ("referred", "Referred"),
                    ("comment", "Comment"),
                    ("overdue", "Overdue"),
                    ("pending", "Pending Deadline"),
                ],
                default="transition",
                max_length=20,
            ),
        ),
    ]
