# Generated by Django 6.0.1 on 2026-03-09 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0029_add_pending_notification_verb"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowGroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_view",
                    models.BooleanField(
                        default=True,
                        help_text="Members of this group can view the workflow",
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Members of this group can edit the workflow",
                    ),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Members of this group can delete the workflow",
                    ),
                ),
                (
                    "can_transition",
                    models.BooleanField(
                        default=False,
                        help_text="Members of this group can perform state transitions",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary owning group (typically from WorkflowType.group)",
                    ),
                ),
                (
                    "inherited_from_type",
                    models.BooleanField(
                        default=False,
                        help_text="Access was inherited from WorkflowType configuration",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted this access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_workflow_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_access",
                        to="workflows.group",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_access",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "group__name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_transition", models.BooleanField(default=False)),
                (
                    "allowed_states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If specified, these permissions only apply in these states",
                        related_name="role_workflow_permissions",
                        to="workflows.state",
                    ),
                ),
                (
                    "group_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="workflows.workflowgroupaccess",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_permissions",
                        to="workflows.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role__name"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowgroupaccess",
            index=models.Index(
                fields=["workflow", "group"], name="workflows_w_workflo_e8041c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowgroupaccess",
            index=models.Index(
                fields=["group", "can_view"], name="workflows_w_group_i_fdb1f4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowgroupaccess",
            unique_together={("workflow", "group")},
        ),
        migrations.AddIndex(
            model_name="workflowrolepermission",
            index=models.Index(
                fields=["group_access", "role"], name="workflows_w_group_a_6cc95a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowrolepermission",
            unique_together={("group_access", "role")},
        ),
    ]
