# Generated by Django 6.0.1 on 2026-03-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0031_populate_rbac_from_existing"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowgroupaccess",
            name="workflows_w_group_i_fdb1f4_idx",
        ),
        migrations.AddField(
            model_name="role",
            name="can_assign_workflows",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can assign workflows to other users",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_create_workflows",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can create new workflows for their groups",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_workflows",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can delete workflows in their groups",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_workflows",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can edit workflows in their groups",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_permissions",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can grant/revoke workflow access to other groups",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_transition_workflows",
            field=models.BooleanField(
                default=False,
                help_text="Users with this role can perform state transitions on workflows",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_view_workflows",
            field=models.BooleanField(
                default=True,
                help_text="Users with this role can view workflows in their groups",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgroupaccess",
            name="inherited_from_type",
            field=models.BooleanField(
                default=False,
                help_text="Access was inherited from WorkflowType configuration (legacy)",
            ),
        ),
        migrations.AlterField(
            model_name="workflowgroupaccess",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Primary owning group (typically selected at creation)",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowgroupaccess",
            index=models.Index(fields=["group"], name="workflows_w_group_i_4b65f3_idx"),
        ),
        migrations.RemoveField(
            model_name="workflowgroupaccess",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="workflowgroupaccess",
            name="can_edit",
        ),
        migrations.RemoveField(
            model_name="workflowgroupaccess",
            name="can_transition",
        ),
        migrations.RemoveField(
            model_name="workflowgroupaccess",
            name="can_view",
        ),
    ]
