# Generated by Django 6.0.3 on 2026-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0033_set_role_permission_defaults"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="can_delete_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_edit_workflows",
        ),
        migrations.RemoveField(
            model_name="role",
            name="can_view_workflows",
        ),
        migrations.AddField(
            model_name="statepermission",
            name="can_transition",
            field=models.BooleanField(
                default=False,
                help_text="Can perform transitions from this state (overrides Transition.allowed_roles if set)",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[
                    ("response", "Response"),
                    ("document", "Document"),
                    ("petition", "Petition"),
                    ("other", "Other"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("legislature", "Legislature"),
                    ("house", "House"),
                    ("portfolio_committee", "Portfolio Committee"),
                    ("select_committee", "Select Committee"),
                    ("special_committee", "Special Committee"),
                    ("public_accounts_committee", "Public Accounts Committee"),
                    ("internal_committee", "Internal Committee"),
                    ("ad_hoc_committee", "Ad Hoc Committee"),
                    ("joint_committee", "Joint Committee"),
                    ("administration", "Administration"),
                    ("office", "Office"),
                    ("division", "Division"),
                    ("section", "Section"),
                    ("business_unit", "Business Unit"),
                    ("party", "Party"),
                    ("executive", "Executive"),
                    ("presidency", "Presidency"),
                    ("ministry", "Ministry"),
                    ("department", "Department"),
                    ("province", "Province"),
                    ("premier", "Premier"),
                    ("delegation", "Delegation"),
                ],
                max_length=50,
            ),
        ),
    ]
