# Generated by Django 6.0.3 on 2026-03-14 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0034_remove_crud_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the delegation becomes effective",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the delegation expires (null = indefinite)",
                        null=True,
                    ),
                ),
                (
                    "can_view_workflows",
                    models.BooleanField(
                        default=True,
                        help_text="Delegatee can view delegator's workflows",
                    ),
                ),
                (
                    "can_edit_workflows",
                    models.BooleanField(
                        default=False,
                        help_text="Delegatee can edit delegator's workflows",
                    ),
                ),
                (
                    "can_transition_workflows",
                    models.BooleanField(
                        default=False,
                        help_text="Delegatee can perform transitions on delegator's workflows",
                    ),
                ),
                (
                    "can_receive_assignments",
                    models.BooleanField(
                        default=True,
                        help_text="New workflow assignments to delegator go to delegatee",
                    ),
                ),
                (
                    "can_receive_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Delegatee receives delegator's workflow notifications",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the delegation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this delegation was approved",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this delegation was revoked",
                        null=True,
                    ),
                ),
                (
                    "revoke_reason",
                    models.TextField(
                        blank=True, help_text="Reason for revoking the delegation"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved this delegation (if required)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegatee",
                    models.ForeignKey(
                        help_text="User who receives the delegated permissions",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        help_text="User who is delegating their permissions",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific groups this delegation applies to (empty = all groups)",
                        related_name="delegations",
                        to="workflows.group",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who revoked this delegation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_delegations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflows",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific workflows this delegation applies to (empty = all workflows)",
                        related_name="delegations",
                        to="workflows.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["delegator", "status"],
                        name="workflows_u_delegat_c83735_idx",
                    ),
                    models.Index(
                        fields=["delegatee", "status"],
                        name="workflows_u_delegat_a3a2ff_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="workflows_u_start_d_a05957_idx",
                    ),
                    models.Index(
                        fields=["status", "end_date"],
                        name="workflows_u_status_0f306a_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gt", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="delegation_end_after_start",
                    )
                ],
                "unique_together": {("delegator", "delegatee", "start_date")},
            },
        ),
    ]
