# Generated by Django 6.0.3 on 2026-03-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0036_alter_notification_verb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="referred_to",
        ),
        migrations.AddField(
            model_name="workflow",
            name="referred_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups this workflow is referred to",
                related_name="referred_workflows",
                to="workflows.group",
            ),
        ),
        migrations.AlterField(
            model_name="workflowreferral",
            name="config",
            field=models.ForeignKey(
                blank=True,
                help_text="The referral config that governs permissions for this referral (deprecated)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referral_instances",
                to="workflows.workflowtypereferralconfig",
            ),
        ),
    ]
