# Generated by Django 6.0.3 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0037_remove_workflow_referred_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="allows_referrals",
            field=models.BooleanField(
                default=True,
                help_text="Can workflows in this state be referred to other groups?",
            ),
        ),
        migrations.AddField(
            model_name="workflowreferral",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Deadline for referral response (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowreferral",
            name="deadline_notified",
            field=models.BooleanField(
                default=False, help_text="Whether deadline notifications have been sent"
            ),
        ),
    ]
