# Generated by Django 6.0.3 on 2026-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0038_referral_system_enhancements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("transition", "Transition"),
                    ("assigned", "Assigned"),
                    ("referred", "Referred"),
                    ("comment", "Comment"),
                    ("overdue", "Overdue"),
                    ("pending", "Pending Deadline"),
                    ("delegation_created", "Delegation Created"),
                    ("delegation_approved", "Delegation Approved"),
                    ("delegation_revoked", "Delegation Revoked"),
                    ("delegation_expired", "Delegation Expired"),
                    ("deadline_warning", "Deadline Warning"),
                    ("auto_recall", "Auto Recall"),
                ],
                default="transition",
                max_length=20,
            ),
        ),
    ]
