# Generated by Django 6.0.3 on 2026-03-18 22:15

from django.db import migrations, models


def migrate_role_to_roles(apps, schema_editor):
    """
    Migrate existing single role FK to ManyToManyField.
    This runs before the role field is removed.
    """
    StatePermission = apps.get_model('workflows', 'StatePermission')
    
    # Store existing role data in a temporary structure
    for permission in StatePermission.objects.all():
        if permission.role_id:
            permission._temp_role_id = permission.role_id
            permission.save()


def finalize_migration(apps, schema_editor):
    """
    Finalize the migration by adding roles to the ManyToManyField.
    This runs after the roles field has been added.
    """
    StatePermission = apps.get_model('workflows', 'StatePermission')
    
    for permission in StatePermission.objects.all():
        if hasattr(permission, '_temp_role_id'):
            permission.roles.add(permission._temp_role_id)


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0039_add_deadline_notification_verbs'),
    ]

    operations = [
        # Step 1: Store existing role data
        migrations.RunPython(migrate_role_to_roles, migrations.RunPython.noop),
        
        # Step 2: Add the new ManyToManyField
        migrations.AddField(
            model_name='statepermission',
            name='roles',
            field=models.ManyToManyField(related_name='state_permissions', to='workflows.role'),
        ),
        
        # Step 3: Update model options
        migrations.AlterModelOptions(
            name='statepermission',
            options={'ordering': ['state']},
        ),
        migrations.AlterUniqueTogether(
            name='statepermission',
            unique_together=set(),
        ),
        
        # Step 4: Migrate data to the new field
        migrations.RunPython(finalize_migration, migrations.RunPython.noop),
        
        # Step 5: Remove the old role field
        migrations.RemoveField(
            model_name='statepermission',
            name='role',
        ),
        
        # Step 6: Update notification field (unrelated but included in original migration)
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[
                    ('transition', 'Transition'),
                    ('assigned', 'Assigned'),
                    ('referred', 'Referred'),
                    ('comment', 'Comment'),
                    ('overdue', 'Overdue'),
                    ('pending', 'Pending Deadline'),
                    ('delegation_created', 'Delegation Created'),
                    ('delegation_approved', 'Delegation Approved'),
                    ('delegation_revoked', 'Delegation Revoked'),
                    ('delegation_expired', 'Delegation Expired'),
                ],
                default='transition',
                max_length=20,
            ),
        ),
    ]
