# Generated by Django 6.0.3 on 2026-03-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0040_change_statepermission_role_to_manytomany"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sitemember",
            unique_together={("site", "user")},
        ),
    ]
