# Generated by Django 6.0.3 on 2026-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0041_alter_sitemember_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attachment",
            unique_together={("related_workflow", "item_id")},
        ),
    ]
