"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

"""

import logging

import ldap
from decouple import config
from django_auth_ldap.config import GroupOfNamesType, LDAPSearch

# LDAP Configuration for Active Directory
ldap.set_option(
    ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_ALLOW
)  # matches the per-connection option

# LDAP Server Configuration
AUTH_LDAP_SERVER_URI = config("AUTH_LDAP_SERVER_URI", default="")
AUTH_LDAP_BIND_DN = config("AUTH_LDAP_BIND_DN", default="")
AUTH_LDAP_BIND_PASSWORD = config("AUTH_LDAP_BIND_PASSWORD", default="")
AUTH_LDAP_BASE_DN = config("AUTH_LDAP_BASE_DN", default="")

# Conditional LDAP configuration
if AUTH_LDAP_BASE_DN:
    # LDAP User Search
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        AUTH_LDAP_BASE_DN,
        ldap.SCOPE_SUBTREE,
        "(|(sAMAccountName=%(user)s)(userPrincipalName=%(user)s)(mail=%(user)s))",
    )

    # LDAP User Attributes Mapping
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "sAMAccountName",
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }

    # # LDAP Group Configuration (optional)
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        AUTH_LDAP_BASE_DN, ldap.SCOPE_SUBTREE, "(objectClass=group)"
    )
    AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()

    # Populate Django user model from LDAP
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    AUTH_LDAP_FIND_GROUP_PERMS = True
    AUTH_LDAP_MIRROR_GROUPS = True

    # Start TLS (optional, set to False if not using TLS)
    AUTH_LDAP_START_TLS = False

    # Allow LDAP authentication to fail gracefully and fall back to ModelBackend
    # This prevents LDAP connection errors from blocking all authentication
    AUTH_LDAP_AUTHORIZE_ALL_USERS = False
    AUTH_LDAP_CACHE_TIMEOUT = 3600

    # LDAP Logging for debugging
    logger = logging.getLogger("django_auth_ldap")
    logger.addHandler(logging.StreamHandler())
    logger.setLevel(logging.DEBUG)

    # === Essential options for Active Directory ===
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0,  # AD referrals break everything if not disabled
        ldap.OPT_NETWORK_TIMEOUT: 5,  # Reduced timeout to fail fast (5 seconds)
        ldap.OPT_TIMEOUT: 5,  # Overall operation timeout
        # This tells OpenSSL/python-ldap to skip CA verification
        # Perfectly safe when you fully control both ends (internal AD)
        ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_ALLOW,
    }

    # Authentication backends include LDAP
    AUTHENTICATION_BACKENDS = [
        "workflows.backends.GracefulLDAPBackend",  # LDAP with graceful error handling
        "workflows.backends.FallbackModelBackend",  # Django fallback with logging
    ]
else:
    # LDAP not configured, use only Django ModelBackend
    AUTHENTICATION_BACKENDS = [
        "workflows.backends.FallbackModelBackend",  # Django fallback with logging
    ]
